services:
  - type: web
    name: ysrcp-dashboard-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RAPIDAPI_KEY
        value: 922556e08bmsh465b2b5025c11a5p176967jsn3ca78cdb094c
      - key: PYTHON_VERSION
        value: 3.11.0
